### ISSUE TITLE
Unknown issue with Google play services 

### ISSUE THREAD

**Issue by vamsipidugu** [googledrive/android-quickstart#2]
Log:

I/BaseDriveActivity(5657): GoogleApiClient connection failed: ConnectionResult{statusCode=INTERNAL_ERROR, resolution=null}

always showing same error, am using Eclipse KEPLER and gooleplayservices rev 14, help me to solve this issue

![screenshot_2014-02-18-12-31-01 1](https://f.cloud.github.com/assets/2044214/2192590/8c4c5210-986a-11e3-9512-b1332e7796b6.png)

**Comment by uxyrather** [comment]
1.I am using android studio 1.1.0.
2.I created a .jks file stored it somewhere on my machine.
3.Used keytool from java jdk and got the SHA1 hashes.
4.Followed the  Google drive api guide and Console guides
5 setup my app for example code. Now i am getting this "Unknown issue with google play service"
Please Guide me !

**Comment by seanpjanson** [comment]
Did you look here? 
http://stackoverflow.com/questions/28532206/google-oauth-2-0-and-debug-key-for-google-drive-api

Another area that can cause your problem is discussed here:
http://stackoverflow.com/questions/28405205/error-com-google-android-gms-drive-driveapi-drivecontentsresult-cannot-be-resolv - library version mismatch.

Or, it may be related to your installation of Google Play Services, step 1 in this SO answer
http://stackoverflow.com/questions/28439129/how-to-acknowledge-when-user-doesnt-want-to-connect-to-google-play-services

**Comment by uxyrather** [comment]
seanpjanson : Thanks for replying i double checked all three answers and itstill didn't help

**Comment by seanpjanson** [comment]
First I would recommend to take these issues directly to SO,
tag [google-drive-android-api], the audience there is wider and you have a
better chance to get an answer.
Second, since you are on Android Studio 1.1, you may try to pull this
project:
https://github.com/seanpjanson/GDAADemo
and step through the MainActivity, where this stuff is hashed out. Sorry,
no other ideas here.
sean

**Comment by ajaybarvey** [comment]
This error "GoogleApiClient connection failed: ConnectionResult{statusCode=INTERNAL_ERROR, resolution=null} " occurs if you have not created credentials for your application.

Go to consolge- https://console.cloud.google.com/apis/credentials
Click on Create Credentials
Add the projectname, SHA key & package name
Run the project and the application should work.
I faced issue running android-quickstart-master and the issue got resolved after following the above steps.
