### ISSUE TITLE
not woking

### ISSUE THREAD

**Issue by pashtetbezd** [googledrive/android-quickstart#7]
after choose account app recall account choose dialog

**Comment by pmk2429** [comment]
Same issue. Did you find a solution to it yet?

**Comment by Alcha** [comment]
I fixed this by moving the code in onResume() to onCreate(). My onCreate looks like:

```
@Override
protected void onCreate(Bundle savedInstanceState) {
	super.onCreate(savedInstanceState);
	if (mGoogleApiClient == null) {
		// Create the API client and bind it to an instance variable.
        // We use this instance as the callback for connection and connection
        // failures.
        // Since no account name is passed, the user is prompted to choose.
        mGoogleApiClient = new GoogleApiClient.Builder(this)
			.addApi(Drive.API)
            .addScope(Drive.SCOPE_FILE)
            .addConnectionCallbacks(this)
            .addOnConnectionFailedListener(this)
            .build();
    }
}
```

**Comment by Alcha** [comment]
Apparently my previous solution wasn't the actual fix. The real issue with my situation was the SHA1 value I put in the Google Developers Console was created with my production keystore alias. I had to create the SHA1 using the debug keystore and after updating it in the Google Developers Console it worked without an issue.

**Comment by amirfarazmand** [comment]
I tried making a debug keystore and added the SHA1 to developer console but the app crashes after authorizing the access. Does this need to be in production to work?

**Comment by sweetflowe** [comment]
Yes work

Magen Farmer

**Comment by Muran-Hu** [comment]
@Alcha, could you please share more detail info? Such as how to create SHA1 and use in the code? TIA.

**Comment by Alcha** [comment]
https://developers.google.com/maps/documentation/android-api/signup#release-cert

This was the guide that I followed but here's the few steps I took on Windows:

1. Start a PowerShell console and navigate to C:\Program Files\Java\jdk1.8.0_60\bin.
2. I ran `.\keytool -list -v -keystore "C:\Users\<Username>\.android\debug.keystore" -alias
androiddebugkey -storepass android -keypass android` and it output the sha1 value.
3. Use the output sha1 value in the developers console to complete the registration of your app.

If this wasn't enough information let me know and I'll go back and write up something easier to understand. It's been a while since I dealt with this so I don't remember every other step I took.

**Comment by Muran-Hu** [comment]
@Alcha, Thanks very much for you help. I noticed that the document you provided is for maps android api, does this also apply for Google Drive development?

Thanks Muran

**Comment by Alcha** [comment]
I'm not sure all of it is the same but when it comes to generating the SHA1 value it does indeed apply. I used the Google Maps docs because the docs for Google Maps isn't quite as descriptive when it comes to this. Here's a link to show you what I mean:
https://developers.google.com/drive/android/auth#generate_the_signing_certificate_fingerprint_and_register_your_application

To be more specific, the Drive docs only mention the overall idea of how to accomplish this which is fine if you're a bit more familiar with these things, but starting out the Maps docs are more valuable as they specifically mention the difference between a debug certificate and a release (read: production) certificate. 

They also do you the favor of mentioning where the *.keystore file is located by default whereas I didn't see that in the Drive docs.

**Comment by Alcha** [comment]
@amirfarazmand, if you generated the SHA1 value using your debug keystore then you shouldn't have to be in production since that's the whole point in generating this value with the debug keystore (as far as I understand it). Generating the SHA1 value with the debug keystore lets you run the app from Android Studio to test it works properly without having to build a production style apk.

Do you happen to get any error message on crash? Even if it's a really vague error, it could help out in some way or another.

**Comment by amirfarazmand** [comment]
@Alcha , I got the SHA1 value fro Google Developer Console, not sure if I am on the right place there. Where do you get the development SHA1, is this still from the Google Developer Console? Thanks. Amir

**Comment by Alcha** [comment]
Read my comment just before the one I tag you in, I mention how to get the development/debug SHA1 value. If that's not clear enough just let me know and I'll see what I can do to explain it better.

**Comment by tomoima525** [comment]
Same issue here.
@Alcha @Muran-Hu 
I read the document [here](https://developers.google.com/drive/android/java-client#set_mime_types_in_the_app_manifest) and it says setup ID on my AndroidManifest.xml, but what exactly is "ID" here? The one generated at Developer console? It was something like `1231231-okvc7jbif9gvpqf4kepvgiepb42oo2br.apps.googleusercontent.com` and I set up on the AndroidManifest.xml, but was in vain/

```
        <activity
            android:name="com.google.android.gms.drive.sample.quickstart.MainActivity"
            android:label="@string/app_name" >
            <meta-data android:name="com.google.android.apps.drive.APP_ID" android:value="id=1231231-okvc7jbif9gvpqf4kepvgiepb42oo2br.apps.googleusercontent.com" />
            <intent-filter>
                <action android:name="com.google.android.apps.drive.DRIVE_OPEN" />
                <data android:mimeType="application/vnd.google-apps.drive-sdk.1231231-okvc7jbif9gvpqf4kepvgiepb42oo2br.apps.googleusercontent.com" />
                <data android:mimeType="image/png" />
                <data android:mimeType="image/jpeg" />
                <data android:mimeType="image/jpg" />
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```

**Comment by tomoima525** [comment]
issue solved. Above setting on AndroidManifest.xml was not required.
Looks like it takes time (1day?)to verify OAuth ID.
 
https://developers.google.com/drive/android/get-started#get_an_android_certificate_and_register_your_application

**Comment by Alcha** [comment]
Sorry about not getting back sooner. Glad to know you fixed it though.

**Comment by npomfret** [comment]
Once you've registered an app and have your oauth client id, what do you do with it?

**Comment by mDroidd** [comment]
+1
